name = "NeuroCore"
uuid = "d459d6fe-e785-4cae-bf87-14a4152982ff"
authors = ["Tokazama <zchristensen7@gmail.com>"]
version = "0.2"

[deps]
AxisIndices = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FieldProperties = "127e4479-4c95-493a-afaa-609d38175b70"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticRanges = "d8176aec-3168-11e9-3c98-e3954798be3a"
TimeAxes = "9a9fc9a6-283d-47e9-a2f6-b3a44e559ea3"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisIndices = "0.6"
Colors = "0.9, 0.10, 0.11, 0.12"
CoordinateTransformations = "0.5"
FFTW = "1"
FieldProperties = "0.6"
FixedPointNumbers = "0.6.1, 0.7, 0.8"
GeometryBasics = "0.2"
MappedArrays = "0.2"
NamedDims = "0.2"
StaticArrays = "0.12"
StaticRanges = "0.7"
Unitful = "1"
Reexport = "0.2"
julia = "1"
TimeAxes = "0.4"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
